/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerInterGrafica;
import controller.ListModelExercicio;
import controller.TableModelTreino;
import domain.Aluno;
import domain.Exercicio;
import domain.Treino;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Xacar
 */
public class TreinoJD extends javax.swing.JDialog {
    private TableModelTreino modelTreino = new TableModelTreino();
    javax.swing.DefaultListModel modelExercicio;
    private GerInterGrafica gerIG;
    private Aluno aluno;
     
    /**
     * Creates new form TreinoJD
     */
    public TreinoJD(java.awt.Frame parent, boolean modal,GerInterGrafica gerIG,Aluno alun){
        super(parent, modal);
        this.gerIG = gerIG;
        initComponents();
        try {
            System.out.println("ooooooooooooooooooooooooooo");
            carregarLista(gerIG.getGerDominio().listar(Exercicio.class));
            setAluno(alun);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao inicializar a tela de treino: " + e.getMessage(), "Erro Crítico", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        
    }

    public void setAluno(Aluno aluno){
        
        this.aluno = aluno;
        gerIG.getGerDominio().carregarTreino(aluno);
        alunoLB.setText(aluno.getNome());
        Collections.sort(aluno.getTreinos());
        modelTreino.setList(aluno.getTreinos());
        treinoTB.setModel(modelTreino);
        treinoTB.updateUI();
        diaCB.setModel(new javax.swing.DefaultComboBoxModel(aluno.getTreinos().toArray()));
        diaCB.updateUI();
        treinoTB.updateUI();
    }
    
    public Exercicio obterExercicio(){
        String nome = nomeTF.getText();
        String grupo = (String) gpMuscularCB.getSelectedItem();
        int repeticoes = (int) qtdRepeticoesSP.getValue();
        int series = (int) qtdSerieSP.getValue();
        Exercicio exercicio = new Exercicio(nome,grupo,series,repeticoes);
        return exercicio;
    }
    
    public void carregarLista(List<Exercicio> exercicios){
        modelExercicio = new javax.swing.DefaultListModel();
            for (Exercicio e : exercicios) {
                modelExercicio.addElement(e);
            }
        exercicioLT.setModel(modelExercicio);
            
    }
    
     private boolean validarExercicio() {
        if (nomeTF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Nome' do exercício é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            nomeTF.requestFocus();
            return false;
        }
        if ((int) qtdSerieSP.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade de 'Séries' deve ser maior que zero.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            qtdSerieSP.requestFocus();
            return false;
        }
        if ((int) qtdRepeticoesSP.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade de 'Repetições' deve ser maior que zero.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            qtdRepeticoesSP.requestFocus();
            return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        treinoTB = new javax.swing.JTable();
        removerTreinoBT = new javax.swing.JButton();
        alterarTreinoBT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        diaCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        alunoLB = new javax.swing.JLabel();
        cadastrarBT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gpMuscularCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        qtdSerieSP = new javax.swing.JSpinner();
        qtdRepeticoesSP = new javax.swing.JSpinner();
        consultarBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        exercicioLT = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        removerSistemaBT = new javax.swing.JButton();
        addBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo Academia Axi (1).jpeg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Alterar/Adicionar Treino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Treino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        treinoTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(treinoTB);

        removerTreinoBT.setText("Remover exercicio do treino");
        removerTreinoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTreinoBTActionPerformed(evt);
            }
        });

        alterarTreinoBT.setText("Alterar Treino");
        alterarTreinoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarTreinoBTActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dia de treino:");

        diaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(diaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(removerTreinoBT)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(alterarTreinoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerTreinoBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarTreinoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aluno:");

        alunoLB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        alunoLB.setForeground(new java.awt.Color(255, 255, 255));
        alunoLB.setText("Fulano da Silva");

        cadastrarBT.setText("Cadastrar exercicio");
        cadastrarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBTActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grupo Muscular:");

        gpMuscularCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costas", "Peito", "Perna", "Braço" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantidade de Series:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantidade de Repetições:");

        qtdSerieSP.setModel(new javax.swing.SpinnerNumberModel());

        qtdRepeticoesSP.setModel(new javax.swing.SpinnerNumberModel());

        consultarBT.setText("Consultar Exercicio");
        consultarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBTActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(exercicioLT);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Exercicios:");

        removerSistemaBT.setText("Remover exercicio do sistema");
        removerSistemaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerSistemaBTActionPerformed(evt);
            }
        });

        addBT.setText("Adicionar exercicio ao treino");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtdSerieSP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(gpMuscularCB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(qtdRepeticoesSP, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(consultarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cadastrarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1)
                            .addComponent(removerSistemaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1057, 1057, 1057))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alunoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alunoLB))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpMuscularCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdSerieSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtdRepeticoesSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultarBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBT))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerSistemaBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        int exIndex = exercicioLT.getSelectedIndex();
        int diaIndex = diaCB.getSelectedIndex();

        if (exIndex == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um exercício da lista para adicionar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (diaIndex == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um dia de treino.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Exercicio ex = (Exercicio) modelExercicio.getElementAt(exIndex);
            Treino treinoDoDia = (Treino) diaCB.getSelectedItem();
            
            if (treinoDoDia.getExercicios().contains(ex)) {
                JOptionPane.showMessageDialog(this, "Este exercício já foi adicionado ao treino deste dia.", "Exercício Duplicado", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            treinoDoDia.addExercicio(ex);
            modelTreino.fireTableDataChanged();
            treinoTB.updateUI();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao adicionar o exercício: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addBTActionPerformed

    private void cadastrarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBTActionPerformed
         if (!validarExercicio()) {
            return;
        }
        
        int confirma = JOptionPane.showConfirmDialog(this, "Deseja cadastrar este novo exercício no sistema?", "Confirmar Cadastro", JOptionPane.YES_NO_OPTION);
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            gerIG.getGerDominio().inserir(obterExercicio());
            JOptionPane.showMessageDialog(this, "Exercício cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            nomeTF.setText("");
            qtdRepeticoesSP.setValue(1);
            qtdSerieSP.setValue(1);
            carregarLista(gerIG.getGerDominio().listar(Exercicio.class));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar exercício: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarBTActionPerformed

    private void diaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaCBActionPerformed

    private void removerTreinoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTreinoBTActionPerformed
       int colum = treinoTB.getSelectedColumn();
       int row = treinoTB.getSelectedRow();

        if (colum == -1||row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um exercicio na tabela de treino.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        
        int confirma = JOptionPane.showConfirmDialog(this, "Deseja remover o exercício selecionado deste treino?", "Confirmar Remoção", JOptionPane.YES_NO_OPTION);
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            modelTreino.getTreino(colum).getExercicios().remove(row);
            aluno.setTreinos(modelTreino.getList());
            modelTreino.setList(aluno.getTreinos());
            
            modelTreino.fireTableDataChanged();
            treinoTB.updateUI();
            JOptionPane.showMessageDialog(this, "Exercício removido do treino.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao remover o exercício do treino: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removerTreinoBTActionPerformed

    private void consultarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBTActionPerformed
        try {
            if (nomeTF.getText().trim().isEmpty()) {
                carregarLista(gerIG.getGerDominio().listar(Exercicio.class));
            } else {
                carregarLista(gerIG.getGerDominio().pesquisarExercicioPorNome(nomeTF.getText()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar exercícios: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_consultarBTActionPerformed

    private void alterarTreinoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarTreinoBTActionPerformed
            
        int confirma = JOptionPane.showConfirmDialog(this, 
                "Deseja salvar todas as alterações feitas no treino deste aluno?", 
                "Confirmar Alterações", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            gerIG.getGerDominio().alterar(this.aluno);
            JOptionPane.showMessageDialog(this, "Treino do aluno salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar as alterações: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarTreinoBTActionPerformed

    private void removerSistemaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerSistemaBTActionPerformed
        int exIndex = exercicioLT.getSelectedIndex();
        if (exIndex == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um exercício da lista para remover do sistema.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Exercicio ex = (Exercicio) modelExercicio.getElementAt(exIndex);
        
        int confirma = JOptionPane.showConfirmDialog(this,
                "Atenção! Esta ação removerá o exercício '" + ex.getNome() + "' permanentemente do sistema.\n"
                + "Isso pode afetar o treino de outros alunos.\n\nDeseja continuar?",
                "Remoção Permanente",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
        if (confirma != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Confirmação extra para segurança
        int confirmaFinal = JOptionPane.showConfirmDialog(this, "Confirmação final: remover permanentemente o exercício?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if(confirmaFinal != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            gerIG.getGerDominio().excluir(ex);
            JOptionPane.showMessageDialog(this, "Exercício removido do sistema com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            carregarLista(gerIG.getGerDominio().listar(Exercicio.class));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover exercício do sistema: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removerSistemaBTActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton alterarTreinoBT;
    private javax.swing.JLabel alunoLB;
    private javax.swing.JButton cadastrarBT;
    private javax.swing.JButton consultarBT;
    private javax.swing.JComboBox<String> diaCB;
    private javax.swing.JList<String> exercicioLT;
    private javax.swing.JComboBox<String> gpMuscularCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JSpinner qtdRepeticoesSP;
    private javax.swing.JSpinner qtdSerieSP;
    private javax.swing.JButton removerSistemaBT;
    private javax.swing.JButton removerTreinoBT;
    private javax.swing.JTable treinoTB;
    // End of variables declaration//GEN-END:variables
}
